### ISSUE TITLE
Serialization of higher order function

### ISSUE THREAD

**Issue by anasanjaria** [romix/akka-kryo-serialization#118]
Here is my case class 
`case class MyCaseClass(num: String, callback: Int => Unit)`

and I am using it with akka-actor (as an argument). Since it is using higher order function hence serialization is not working properly. I have found a solution [here](https://stackoverflow.com/a/9770788/665905) and it is working. But I don't want to use this solution as I need to make a lot of changes. 

Can you suggest me better way of doing that?

**Comment by luben** [comment]
Hi @anasanjaria,

Kryo serialization is nominal, i.e. it depend on the name of the class to be able to reconstruct the exact same instance on the other side. So the suggestion to use classes that extend FunctionX[A,B] is the best solution at the moment.

Another option is to use quasi-quotes that are materializing the scala computation as AST and transfer the AST but I think it will be a lot more invasive and complex change than creating a named instances of FunctionX.

Regards,

**Comment by anasanjaria** [comment]
@luben thank you so much for your response. I have fixed this issue by using [twitter-chill](https://github.com/twitter/chill#chill-akka), an extension of kryo.

**Comment by luben** [comment]
It's worth seeing how is done in Chill and take the same approach
