### ISSUE TITLE
Please publish the OSGi bundle version on Maven Central

### ISSUE THREAD

**Issue by magnet** [romix/akka-kryo-serialization#26]
The version currently on Maven Central (0.3.1) doesn't have the proper OSGi headers in its manifest. It would be very practical to always publish them as it doesn't hurt non-OSGi users & helps OSGi users a lot (especially since the Akka distribution is getting more & more OSGi compatible).

I saw the build already supports OSGi so it would be very nice to publish an OSGi-compatible 0.3.2 version.

Thanks!

**Comment by briantopping** [comment]
This is probably addressed by #64
