### ISSUE TITLE
please publish the 0.3.3 verison of akka-kryo-serialization_2.10

### ISSUE THREAD

**Issue by yousef-fadila** [romix/akka-kryo-serialization#50]
Hi 
Not an issue in the project, but as this version used as in example in the readme.md, it supposed to be exist in the repo. 

the version 0.3.3 is not published on 
http://search.maven.org/#browse|-1023511903 

    <dependency>
        <groupId>com.github.romix.akka</groupId>
        <artifactId>akka-kryo-serialization_2.10</artifactId>
        <version>0.3.3</version>
    </dependency>

**Comment by romix** [comment]
Yes, it has to look like this:

```xml
<dependency>
    <groupId>com.github.romix.akka</groupId>
    <artifactId>akka-kryo-serialization_2.11</artifactId>
    <version>0.3.3</version>
</dependency>
```

**Comment by yousef-fadila** [comment]
could you publish version compiled with  scala 2.10  ?
