### ISSUE TITLE
ScalaMapSerializer referenced at the README doesn't exist

### ISSUE THREAD

**Issue by sortega** [romix/akka-kryo-serialization#54]
Hello,

I'm trying to make version 0.3.3 serialize Scala maps following the instructions on the README. I'm unable to find the ScalaMapSerializer class that is referenced in the instructions.

Thanks in advance

**Comment by romix** [comment]
You are right! The classes for map serialization are called differently now. It is `ScalaMutableMapSerializer`, `ScalaImmutableMapSerializer`, `SortedMapSerializer`.

We need to update the docs.

**Comment by sortega** [comment]
I tried replacing ScalaMapSerializer by ScalaImmutableMapSerializer and it didn´t work.
