### ISSUE TITLE
Version `0.4.0` not on Maven Central

### ISSUE THREAD

**Issue by pstutz** [romix/akka-kryo-serialization#59]
Couldn't find it at http://repo1.maven.org/maven2/com/github/romix/akka/akka-kryo-serialization_2.11/ or at http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.romix.akka%22%20AND%20a%3A%22akka-kryo-serialization_2.11%22

**Comment by guidomedina** [comment]
Can confirm, I wasn't going to ask hoping that maybe was a cache issue but it is not almost 24 hours.

**Comment by romix** [comment]
It should be available on maven central now.

**Comment by pstutz** [comment]
Thank you very much.
