### ISSUE TITLE
Top-level class in the serialization-binding is not enough

### ISSUE THREAD

**Issue by jonasrichard** [romix/akka-kryo-serialization#87]
I set up a simple project with two messages having a common root (it is an abstract class but it was a trait).

```scala
package hu.jonas.cluster

abstract class ClusterMessage
final case class Status() extends ClusterMessage
final case class StatusReply(status: String) extends ClusterMessage
```
I am using kryo as a serializer, here is my config file (it is not a full config since I am including the serialization.conf from a client and a server app - same source root).

```
akka {
  extensions = ["com.romix.akka.serialization.kryo.KryoSerializationExtension$"]

  actor {
    kryo {
      type = "graph"
      idstrategy = "incremental"
      buffer-size = 4096
      max-buffer-size = -1
      use-manifest = false
      implicit-registration-logging = true
      kryo-trace = true

      mappings {
        "hu.jonas.cluster.ClusterMessage" = 32,
        "hu.jonas.cluster.Status" = 33,
        "hu.jonas.cluster.StatusReply" = 34
      }
    }

    serialize-messages = on
    serializers {
      #java = "akka.serialization.JavaSerializer"
      kryo = "com.romix.akka.serialization.kryo.KryoSerializer"
    }
    serialization-bindings {
      "hu.jonas.cluster.ClusterMessage" = kryo
      "hu.jonas.cluster.Status" = kryo
      "hu.jonas.cluster.StatusReply" = kryo
    }
  }
}
```

The problem is that if I left out the `Status` and `StatusReply` lines from the `serialization-binding`, akka wants to use the default Java serializer (even though I commented out). Okay the second part may not be your business, but according to the (akka docs)[http://doc.akka.io/docs/akka/2.4.2/scala/serialization.html#Configuration] it is enough to list the top level class of the messages.

Do you have an idea why kryo doesn't want to serialize the messages (the mappings remained of course).

Scala: 2.11.8 Akka: 2.4.2 Kryo: 0.4.0

**Comment by jonasrichard** [comment]
My source repo is [here](https://github.com/jonasrichard/simple-cluster).

**Comment by luben** [comment]
Are you getting a warning saying "Multiple serializers found for class ... choosing first: ..." ?

I think when configuring "serialization-bindings" you add preferred serializer but don't remove the java serializer that stays as the default one for the classes implementing Serializable interface. I guess because the case classes/objects implement Serializable you will get the warning (both Java and Kryo serializers have the same level of specificity for the case classes).

What happens if you declare your ClusterMessage as a trait and the concrete messages as final classes (not case classes)? I think Akka should pick Kryo without a warning.

**Comment by luben** [comment]
another option is to define `ClusterMessage` as:
```scala
  trait  ClusterMessage extends Serializable
```
it this way the Serializable interface will become less specific and will not be considered

**Comment by jonasrichard** [comment]
I want to pattern match on my messages so I don't really want to reimplement everything what case classes provide me. But your second advice is the winner. Thanks.
Even if I commented out java serializer (maybe because case classes implement Serializable) the messages wanted to be serialized by java serializer.
This trait extend Serializable trick works. Probably it should be written in the documentation somehow. Notes about case classes or whatever.
