### ISSUE TITLE
Upgrade to Kryo 4?

### ISSUE THREAD

**Issue by TimPigden** [romix/akka-kryo-serialization#98]
Hi, I've spent a few hours tracking down a bug which turns out to be because kryo 3.xx prior to March of this year did not correctly serialize java.time.ZonedDateTime - specifically when the "Z" time offset is used.
It looks like this is now fixed, but akka-kryo-serialization is still on an older version of Kryo.
Is there any imminent plan to update Kryo versions?
Thanks

**Comment by luben** [comment]
I think we should bump the version to 0.5.0 for the Kryo 4 upgrade as the compression format is incompatible by default.

**Comment by romix** [comment]
Done.
